export const rotateStyle = [
  '[&_.ol-rotate]:absolute',
  '[&_.ol-rotate_button]:none',
  '[&_.ol-rotate]:flex-row',
  '[&_.ol-rotate]:text-transparent',
  '[&_.ol-rotate]:w-[25px]',
  '[&_.ol-rotate]:h-[25px]',
  '[&_.ol-rotate]]:bg-transparent',
  "[&_.ol-rotate]:bg-[url('/assets/icons/north.svg')]",
  '[&_.ol-rotate]:bg-no-repeat',
  '[&_.ol-rotate]:right-[1rem]',
  '[&_.ol-rotate]:top-[58rem]',
  '[&_.ol-rotate:hover]:scale-[120%]',
];

export const fullScreenStyle = [
  '[&_.ol-full-screen]:absolute',
  '[&_.ol-full-screen_button]:none',
  '[&_.ol-full-screen]:text-transparent',
  '[&_.ol-full-screen]:w-[25px]',
  '[&_.ol-full-screen]:h-[25px]',
  "[&_.ol-full-screen]:bg-[url('/assets/icons/Extent.svg')]",
  '[&_.ol-full-screen]:bg-no-repeat',
  '[&_.ol-full-screen]:right-[1rem]',
  '[&_.ol-full-screen]:top-[60rem]',
  '[&_.ol-full-screen:hover]:scale-[140%]',
  '[&_.ol-full-screen_button]:w-[1.5rem]',
  '[&_.ol-full-screen_button]:h-[1.5rem]',
  '[&_.ol-full-screen_button]: text-xl',
];

export const zoomInStyle = [
  '[&_.ol-zoom-in]:absolute',
  '[&_.ol-zoom-in_button]:none',
  '[&_.ol-zoom-in]:text-transparent',
  '[&_.ol-zoom-in]:w-[25px]',
  '[&_.ol-zoom-in]:h-[35}px]',
  "[&_.ol-zoom-in]:bg-[url('/assets/icons/zoom_in.svg')]",
  '[&_.ol-zoom-in]:bg-no-repeat',
  '[&_.ol-zoom-in]:right-[1rem]',
  '[&_.ol-zoom-in]:top-[54rem]',
  '[&_.ol-zoom-in:hover]:scale-[140%]',
  '[&_.ol-zoom-in_button]:w-[1.5rem]',
  '[&_.ol-zoom-in_button]:h-[1.5rem]',
  '[&_.ol-zoom-in_button]: text-xl',

  // Add white box
  '[&_.ol-zoom-in::before]:content-[""]',
  '[&_.ol-zoom-in::before]:block',
  '[&_.ol-zoom-in::before]:absolute',
  '[&_.ol-zoom-in::before]:right-[5rem]',
  '[&_.ol-zoom-in::before]:top-[54rem]',
  '[&_.ol-zoom-in::before]:w-[30px]',
  '[&_.ol-zoom-in::before]:h-[30px]',
  '[&_.ol-zoom-in::before]:bg-[white]',
  '[&_.ol-zoom-in::before]:box-border',
  '[&_.ol-zoom-in::before]:border-2',
  '[&_.ol-zoom-in::before]:border-solid',
  '[&_.ol-zoom-in::before]: border-[black]',
];

export const zoomOutStyle = [
  '[&_.ol-zoom-out]:absolute',
  '[&_.ol-zoom-out]:text-transparent',
  '[&_.ol-zoom-out]:w-[25px]',
  '[&_.ol-zoom-out]:h-[25px]',
  '[&_.ol-zoom-out]:bg-transparent',
  "[&_.ol-zoom-out]:bg-[url('/assets/icons/zoom_out.svg')]",
  '[&_.ol-zoom-out]:bg-no-repeat',
  '[&_.ol-zoom-out]:border-[none]',
  '[&_.ol-zoom-out]:right-[1rem]',
  '[&_.ol-zoom-out]:top-[56rem]',
  '[&_.ol-zoom-out:hover]:scale-[120%]',
];
